version: 2

project_name: port-detective

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: port-detective
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/pd
    binary: pd

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # Bọc binary trong một thư mục khi giải nén (an toàn)
    wrap_in_directory: true
    # Windows thì xài zip cho tiện dụng
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: Khoa180806
    name: Port_Detective
  draft: false
  prerelease: auto
